services:
  notebook:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work:z
    env_file:
      - .env
    environment:
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
    user: root
    working_dir: /home/jovyan/work